server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
            allowedHeaders: "*"
      routes:
        - id: categories-service
          uri: lb://categories-service
          predicates:
            - Path=/api/categories/**
        - id: brands-service
          uri: lb://brands-service
          predicates:
            - Path=/api/brands/**
        - id: products-service
          uri: lb://products-service
          predicates:
            - Path=/api/products/**