version: '3.7'
services:
  config-service:
    image: config-service
    ports:
      - "8081:8081"
    restart: always
    networks:
      - storemariela
  eureka-service:
    image: eureka-service
    ports:
      - "8761:8761"
    restart: always
    networks:
      - storemariela
    depends_on:
      - config-service
  mongodb:
    image: mongo  
    ports:
      - "27017:27017"
    restart: always
    networks:
      - storemariela
    depends_on:
      - config-service
      - eureka-service
  mysqldb:
    image: mysql  
    ports:
      - "3306:3306"
    restart: always
    networks:
      - storemariela
    depends_on:
      - config-service
      - eureka-service
    environment: 
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: 1234
  auth-service:
    image: auth-service    
    restart: always
    networks:
      - storemariela
    depends_on:
      - config-service
      - eureka-service
  brands-service:
    image: brands-service    
    restart: always
    networks:
      - storemariela
    depends_on:
      - config-service
      - eureka-service
  gateway-service:
    image: gateway-service    
    restart: always
    networks:
      - storemariela
    depends_on:
      - config-service
      - eureka-service
networks:
  storemariela: